function Metricks() {
        return (
                <>
                        <div className="mt-28">
                                <h2 className="md:text-4xl text-3xl font-bold text-center mb-14">Application Metrics</h2>
                                <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
                                        <div className="text-center">
                                                <h3 className="text-4xl font-semibold">5.4<span className="text-blue-600">M+</span></h3>
                                                <p className="text-base font-semibold mt-4">Total Users</p>
                                                <p className="mt-2">The total number of registered users on the platform.</p>
                                        </div>
                                        <div className="text-center">
                                                <h3 className="text-4xl font-semibold">$80<span className="text-blue-600">K</span></h3>
                                                <p className="text-base font-semibold mt-4">Revenue</p>
                                                <p className="mt-2">The total revenue generated by the application.</p>
                                        </div>
                                        <div className="text-center">
                                                <h3 className="text-4xl font-semibold">100<span className="text-blue-600">K</span></h3>
                                                <p className="text-base font-semibold mt-4">Engagement</p>
                                                <p className="mt-2">The level of user engagement with the application's content and features.</p>
                                        </div>
                                        <div className="text-center">
                                                <h3 className="text-4xl font-semibold">99.9<span className="text-blue-600">%</span></h3>
                                                <p className="text-base font-semibold mt-4">Server Uptime</p>
                                                <p className="mt-2">The percentage of time the server has been operational and available.</p>
                                        </div>
                                </div>
                        </div>
                </>
        )
}

export default Metricks;